import type { 全渠道订单, 订单路由, 金额 } from './类型'

const 金额值 = (currency: string, value: string): 金额 => ({ currency, value })

const 万邑通美西: 订单路由 = {
  warehouse: '万邑通美西仓',
  warehouseProvider: '万邑通',
  warehouseAccount: '万邑通 · 北美主体',
  shippingChannel: 'USPS Ground Advantage',
  shippingChannelCode: 'WYT-USPS-GA',
  labelMode: '仓配一体',
}

const 谷仓美东: 订单路由 = {
  warehouse: '谷仓美东仓',
  warehouseProvider: '谷仓',
  warehouseAccount: '谷仓 · 北美主体',
  shippingChannel: 'FedEx Home Delivery',
  shippingChannelCode: 'GC-FEDEX-HD',
  labelMode: '仓配一体',
}

const 四PX巴西: 订单路由 = {
  warehouse: '4PX 巴西圣保罗仓',
  warehouseProvider: '4PX',
  warehouseAccount: '4PX · 拉美主体',
  shippingChannel: 'Correios PAC',
  shippingChannelCode: '4PX-BR-PAC',
  labelMode: '仓配一体',
}

const 西邮波兰: 订单路由 = {
  warehouse: '西邮波兰仓',
  warehouseProvider: '西邮',
  warehouseAccount: '西邮 · 欧洲主体',
  shippingChannel: 'InPost Courier',
  shippingChannelCode: 'XY-PL-INPOST',
  labelMode: '仓配分离',
}

const 出口易德国: 订单路由 = {
  warehouse: '出口易德国仓',
  warehouseProvider: '出口易',
  warehouseAccount: '出口易 · 欧洲主体',
  shippingChannel: 'DHL Paket',
  shippingChannelCode: 'CK1-DE-DHL',
  labelMode: '仓配一体',
}

const 全渠道订单场景: 全渠道订单[] = [
  {
    systemOrderNo: 'OMS260909000184',
    platformCode: 'eBay',
    storeId: 'store-ebay-us-01',
    storeName: '北美底盘配件店',
    platformOrderId: '15-10578-48261',
    platformOrderNo: '15-10578-48261',
    platformOrderType: 'NORMAL',
    platformOrderStatus: 'IN_PROGRESS',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    processingStatus: '待发货',
    defaultRoute: 万邑通美西,
    orderedAt: '2026-09-08 11:24:18 UTC-7',
    paidAt: '2026-09-08 11:26:03 UTC-7',
    shipByAt: '2026-09-10 18:00 UTC-7',
    shipByLabel: '今日 18:00',
    urgency: '今日',
    platformUpdatedAt: '2026-09-09 13:58:42 UTC+8',
    createdAt: '2026-09-09 02:25:01 UTC+8',
    lastSyncedAt: '2026-09-10 09:28:12 UTC+8',
    tags: ['临', '信'],
    buyerExternalId: 'ra***27',
    address: {
      fullName: 'R*** M***',
      mobilePhone: '+1 415 *** 4826',
      email: 'r***@example.com',
      countryCode: 'US',
      stateProvince: 'CA',
      city: 'San F***',
      addressLine1: '*** Market Street',
      addressLine2: 'Suite ***',
      postalCode: '94***',
      buyerMessage: 'Please leave the parcel at the front desk.',
    },
    amount: {
      orderAmount: 金额值('USD', '286.80'),
      buyerPaidShipping: 金额值('USD', '12.90'),
      buyerPaidTax: 金额值('USD', '24.00'),
    },
    items: [
      {
        externalLineId: 'v1|225611043811|0',
        platformItemId: '225611043811',
        platformSku: 'EB-US-CA-1048',
        platformVariant: 'Position: Front Lower',
        platformItemTitle: 'Front Lower Control Arm Kit Compatible with Selected SUV Models',
        orderedQuantity: 1,
        systemSku: 'YY-CA-1048-US',
        systemItemName: '前下控制臂套装',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 1,
        currencyCode: 'USD',
        unitPrice: 金额值('USD', '184.00'),
        itemTotal: 金额值('USD', '184.00'),
        actualReceived: 金额值('USD', '184.00'),
        actualReceivedSource: 'PLATFORM',
      },
      {
        externalLineId: 'v1|225798310426|471992020431',
        platformItemId: '225798310426',
        platformSku: 'EB-US-EM-2207',
        platformVariant: 'Package: Pair',
        platformItemTitle: 'Engine Mount Set — Left and Right Pair',
        orderedQuantity: 2,
        systemSku: 'YY-EM-2207-US',
        systemItemName: '发动机支架左右套装',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 2,
        currencyCode: 'USD',
        unitPrice: 金额值('USD', '51.40'),
        itemTotal: 金额值('USD', '102.80'),
        actualReceived: 金额值('USD', '102.80'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [
      {
        fulfillmentOrderNo: 'FL260909000072',
        status: '执行中',
        isActive: true,
        route: 万邑通美西,
        plannedQuantity: 3,
        shippedQuantity: 1,
        trackingNumber: '94***0031',
      },
    ],
    reviews: [
      {
        round: 1,
        type: '自动审核',
        triggerSource: '首次接入',
        status: '已通过',
        decisionNote: 'SKU 映射、地址、库存及默认路由校验通过；订单进入待推单。',
        completedAt: '2026-09-09 02:26:13 UTC+8',
      },
    ],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 09:28:12 UTC+8',
      latestAttempt: '2026-09-10 09:28:10 UTC+8',
      externalVersion: 'order@2026-09-10T01:28:02Z',
      normalizationStatus: '已标准化',
      message: '平台订单和当前标准化投影均已更新。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-09 02:25:01 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: '平台接入任务',
        content: '创建全渠道订单并关联 eBay 专业订单。',
      },
      {
        operatedAt: '2026-09-09 02:26:13 UTC+8',
        operationType: '自动审核',
        operationResult: '成功',
        operator: '审单规则任务',
        content: '审核通过，已固化默认路由并生成履约单。',
      },
      {
        operatedAt: '2026-09-10 09:28:12 UTC+8',
        operationType: '平台同步',
        operationResult: '成功',
        operator: 'eBay 增量任务',
        content: '更新平台订单状态投影，OMS 处理状态未被平台状态覆盖。',
      },
    ],
    professionalOrder: {
      routeName: 'oms-ebay-order-detail',
      sellerId: 'parts-hub-us',
      orderId: '15-10578-48261',
    },
  },
  {
    systemOrderNo: 'OMS260910000219',
    platformCode: 'Temu',
    storeId: 'store-temu-us-02',
    storeName: 'Temu 北美汽配二店',
    platformOrderId: 'TPO-260910-028419',
    platformOrderNo: 'PO-240910-9284***',
    platformOrderType: 'NORMAL',
    platformOrderStatus: 'READY_TO_SHIP',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    processingStatus: '待推单',
    defaultRoute: 谷仓美东,
    orderedAt: '2026-09-10 00:42:08 UTC-5',
    paidAt: '2026-09-10 00:43:17 UTC-5',
    shipByAt: '2026-09-11 16:00 UTC-5',
    shipByLabel: '明日 16:00',
    urgency: '正常',
    platformUpdatedAt: '2026-09-10 13:05:41 UTC+8',
    createdAt: '2026-09-10 13:06:02 UTC+8',
    lastSyncedAt: '2026-09-10 14:05:43 UTC+8',
    tags: ['新'],
    buyerExternalId: 'tm***819',
    address: {
      fullName: 'A*** J***',
      mobilePhone: '+1 973 *** 1802',
      email: 'a***@example.com',
      countryCode: 'US',
      stateProvince: 'NJ',
      city: 'New***',
      addressLine1: '*** Broad Street',
      postalCode: '07***',
    },
    amount: {
      orderAmount: 金额值('USD', '74.50'),
      buyerPaidShipping: 金额值('USD', '0.00'),
      buyerPaidTax: 金额值('USD', '5.52'),
      platformSubsidy: 金额值('USD', '4.00'),
    },
    items: [
      {
        externalLineId: 'temu-line-028419-01',
        platformItemId: '601099***128',
        platformSku: 'TM-US-WH-7781',
        platformVariant: 'Front axle',
        platformItemTitle: 'Wheel Bearing Hub Assembly Front Axle',
        orderedQuantity: 1,
        systemSku: 'YY-WH-7781-US',
        systemItemName: '前轮毂轴承总成',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 1,
        currencyCode: 'USD',
        unitPrice: 金额值('USD', '74.50'),
        itemTotal: 金额值('USD', '74.50'),
        actualReceived: 金额值('USD', '70.50'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [
      {
        fulfillmentOrderNo: 'FL260910000118',
        status: '待执行',
        isActive: true,
        route: 谷仓美东,
        plannedQuantity: 1,
        shippedQuantity: 0,
      },
    ],
    reviews: [
      {
        round: 1,
        type: '自动审核',
        triggerSource: '首次接入',
        status: '已通过',
        decisionNote: '地址、SKU、库存及默认路由检查通过；已生成当前有效履约单。',
        completedAt: '2026-09-10 13:07:28 UTC+8',
      },
    ],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 14:05:43 UTC+8',
      latestAttempt: '2026-09-10 14:05:40 UTC+8',
      externalVersion: 'change-9081284',
      normalizationStatus: '已标准化',
      message: '订单通用字段已完成增量更新。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-10 13:06:02 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: 'Temu 接入任务',
        content: '创建全渠道订单并完成订单去重。',
      },
      {
        operatedAt: '2026-09-10 13:07:28 UTC+8',
        operationType: '自动审核',
        operationResult: '成功',
        operator: '审单规则任务',
        content: '审核通过，生成履约单 FL260910000118。',
      },
    ],
  },
  {
    systemOrderNo: 'OMS260910000184',
    platformCode: 'Mercado Libre',
    storeId: 'store-ml-br-01',
    storeName: '美客多巴西底盘店',
    platformOrderId: '200001126***841',
    platformOrderNo: 'BR-260910-118***',
    platformOrderType: 'normal',
    platformOrderStatus: 'ready_to_ship',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    processingStatus: '待发货',
    defaultRoute: 四PX巴西,
    orderedAt: '2026-09-09 22:18:36 UTC-3',
    paidAt: '2026-09-09 22:19:03 UTC-3',
    shipByAt: '2026-09-10 17:00 UTC-3',
    shipByLabel: '今日 17:00',
    urgency: '临期',
    platformUpdatedAt: '2026-09-10 12:31:28 UTC+8',
    createdAt: '2026-09-10 09:19:21 UTC+8',
    lastSyncedAt: '2026-09-10 14:11:29 UTC+8',
    tags: ['临'],
    buyerExternalId: 'mlb***572',
    address: {
      fullName: 'C*** S***',
      mobilePhone: '+55 11 *****-7712',
      email: 'c***@example.com.br',
      countryCode: 'BR',
      stateProvince: 'SP',
      city: 'São P***',
      addressLine1: 'Rua ***',
      postalCode: '01***-***',
    },
    amount: {
      orderAmount: 金额值('BRL', '468.90'),
      buyerPaidShipping: 金额值('BRL', '28.90'),
      buyerPaidTax: 金额值('BRL', '0.00'),
      transactionFee: 金额值('BRL', '56.27'),
    },
    items: [
      {
        externalLineId: 'mlb-line-118-01',
        platformItemId: 'MLB38***221',
        platformSku: 'ML-BR-CV-3308',
        platformVariant: 'Kit 2 peças',
        platformItemTitle: 'Junta Homocinética Dianteira Kit 2 Peças',
        orderedQuantity: 1,
        systemSku: 'YY-CV-3308-BR',
        systemItemName: '前轮等速万向节套装',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 1,
        currencyCode: 'BRL',
        unitPrice: 金额值('BRL', '440.00'),
        itemTotal: 金额值('BRL', '440.00'),
        actualReceived: 金额值('BRL', '412.63'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [
      {
        fulfillmentOrderNo: 'FL260910000091',
        status: '执行中',
        isActive: true,
        route: 四PX巴西,
        plannedQuantity: 1,
        shippedQuantity: 0,
      },
    ],
    reviews: [
      {
        round: 1,
        type: '自动审核',
        triggerSource: '首次接入',
        status: '已通过',
        decisionNote: '订单通用校验通过，仓库已明确建单，等待仓内出库。',
        completedAt: '2026-09-10 09:21:42 UTC+8',
      },
    ],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 14:11:29 UTC+8',
      latestAttempt: '2026-09-10 14:11:27 UTC+8',
      externalVersion: 'mlb-updated-20260910T061127Z',
      normalizationStatus: '已标准化',
      message: '平台状态投影与标准订单字段均已更新。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-10 09:19:21 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: '美客多接入任务',
        content: '创建全渠道订单。',
      },
      {
        operatedAt: '2026-09-10 09:29:06 UTC+8',
        operationType: '仓库推单',
        operationResult: '成功',
        operator: '履约任务',
        content: '三方仓已明确建单，订单进入待发货。',
      },
    ],
  },
  {
    systemOrderNo: 'OMS260909000907',
    platformCode: 'Coupang',
    storeId: 'store-coupang-kr-01',
    storeName: 'Coupang 韩国车身件店',
    platformOrderId: 'cp-order-910***772',
    platformOrderNo: '9100***772',
    platformOrderType: 'FULFILLMENT',
    platformOrderStatus: 'DELIVERED',
    orderType: '线上订单',
    fulfillmentMode: '平台履约',
    orderedAt: '2026-09-08 15:17:42 UTC+9',
    paidAt: '2026-09-08 15:17:58 UTC+9',
    shipByLabel: '平台履约',
    urgency: '无时限',
    platformUpdatedAt: '2026-09-10 10:02:11 UTC+9',
    createdAt: '2026-09-08 15:18:19 UTC+9',
    lastSyncedAt: '2026-09-10 09:02:28 UTC+8',
    fulfillmentCompletedAt: '2026-09-10 10:02:11 UTC+9',
    tags: [],
    buyerExternalId: 'cp***590',
    address: {
      fullName: 'K*** M***',
      mobilePhone: '+82 10-****-6281',
      countryCode: 'KR',
      stateProvince: 'Seoul',
      city: 'Seo***',
      addressLine1: '*** Teheran-ro',
      postalCode: '06***',
    },
    amount: {
      orderAmount: 金额值('KRW', '128000'),
      buyerPaidShipping: 金额值('KRW', '0'),
      buyerPaidTax: 金额值('KRW', '0'),
    },
    items: [
      {
        externalLineId: 'cp-line-772-01',
        platformItemId: 'cp-item-77***10',
        platformSku: 'CP-KR-BM-1280',
        platformVariant: 'Black',
        platformItemTitle: 'Side Mirror Assembly Passenger Side',
        orderedQuantity: 1,
        systemSku: 'YY-BM-1280-KR',
        systemItemName: '右侧后视镜总成',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 0,
        currencyCode: 'KRW',
        unitPrice: 金额值('KRW', '128000'),
        itemTotal: 金额值('KRW', '128000'),
        actualReceived: 金额值('KRW', '128000'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [],
    reviews: [],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 09:02:28 UTC+8',
      latestAttempt: '2026-09-10 09:02:26 UTC+8',
      externalVersion: 'cp-v398821',
      normalizationStatus: '已标准化',
      message: '平台履约事实已更新；OMS 订单处理状态不适用。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-08 15:18:19 UTC+9',
        operationType: '订单接入',
        operationResult: '成功',
        operator: 'Coupang 接入任务',
        content: '识别为平台履约订单，仅保存通用订单事实。',
      },
      {
        operatedAt: '2026-09-10 09:02:28 UTC+8',
        operationType: '平台履约同步',
        operationResult: '成功',
        operator: 'Coupang 增量任务',
        content: '更新平台履约状态与履约完成时间。',
      },
    ],
  },
  {
    systemOrderNo: 'OMS260908000455',
    platformCode: 'OZON',
    storeId: 'store-ozon-eu-02',
    storeName: 'OZON 欧洲悬挂件店',
    platformOrderId: 'ozon-posting-88***142',
    platformOrderNo: '088***142-0001',
    platformOrderType: 'FBS',
    platformOrderStatus: 'delivering',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    processingStatus: '已发货',
    defaultRoute: 西邮波兰,
    orderedAt: '2026-09-07 17:26:09 UTC+3',
    paidAt: '2026-09-07 17:27:20 UTC+3',
    shipByAt: '2026-09-09 18:00 UTC+3',
    shipByLabel: '已按时发货',
    urgency: '无时限',
    platformUpdatedAt: '2026-09-10 08:21:55 UTC+3',
    createdAt: '2026-09-07 22:28:03 UTC+8',
    lastSyncedAt: '2026-09-10 13:22:08 UTC+8',
    tags: ['拆'],
    buyerExternalId: 'oz***228',
    address: {
      fullName: 'I*** P***',
      mobilePhone: '+7 *** ***-44-18',
      email: 'i***@example.ru',
      countryCode: 'RU',
      stateProvince: 'Moscow',
      city: 'Mos***',
      addressLine1: 'Ulitsa ***',
      postalCode: '10****',
    },
    amount: {
      orderAmount: 金额值('RUB', '19400.00'),
      buyerPaidShipping: 金额值('RUB', '800.00'),
      buyerPaidTax: 金额值('RUB', '0.00'),
      transactionFee: 金额值('RUB', '2328.00'),
    },
    items: [
      {
        externalLineId: 'oz-line-142-01',
        platformItemId: 'oz-sku-***431',
        platformSku: 'OZ-RU-SA-9055',
        platformItemTitle: 'Front Shock Absorber Assembly',
        orderedQuantity: 2,
        systemSku: 'YY-SA-9055-EU',
        systemItemName: '前减震器总成',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 2,
        currencyCode: 'RUB',
        unitPrice: 金额值('RUB', '9300.00'),
        itemTotal: 金额值('RUB', '18600.00'),
        actualReceived: 金额值('RUB', '16272.00'),
        actualReceivedSource: 'PLATFORM',
      },
      {
        externalLineId: 'oz-line-142-02',
        platformItemId: 'oz-sku-***192',
        platformSku: 'OZ-RU-BU-0210',
        platformItemTitle: 'Suspension Bushing Kit',
        orderedQuantity: 1,
        systemSku: 'YY-BU-0210-EU',
        systemItemName: '悬挂衬套套装',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 1,
        currencyCode: 'RUB',
        unitPrice: 金额值('RUB', '800.00'),
        itemTotal: 金额值('RUB', '800.00'),
        actualReceived: 金额值('RUB', '800.00'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [
      {
        fulfillmentOrderNo: 'FL260908000201',
        status: '已发货',
        isActive: true,
        route: 西邮波兰,
        plannedQuantity: 2,
        shippedQuantity: 2,
        trackingNumber: 'PL***8814',
        shippedAt: '2026-09-09 10:31:26 UTC+2',
      },
      {
        fulfillmentOrderNo: 'FL260908000202',
        status: '已发货',
        isActive: true,
        route: 出口易德国,
        plannedQuantity: 1,
        shippedQuantity: 1,
        trackingNumber: 'DE***2790',
        shippedAt: '2026-09-09 11:18:04 UTC+2',
      },
    ],
    reviews: [
      {
        round: 1,
        type: '人工审核',
        triggerSource: '跨仓拆单',
        status: '已通过',
        decisionNote: '单仓库存不足，按商品行拆分至西邮波兰仓与出口易德国仓；两张履约单均已确认。',
        completedAt: '2026-09-08 09:41:02 UTC+8',
      },
    ],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 13:22:08 UTC+8',
      latestAttempt: '2026-09-10 13:22:05 UTC+8',
      externalVersion: 'ozon-evt-901233',
      normalizationStatus: '已标准化',
      message: '平台订单状态已更新；两张当前有效履约单均已形成出库事实。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-07 22:28:03 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: 'OZON 接入任务',
        content: '创建全渠道订单。',
      },
      {
        operatedAt: '2026-09-08 09:41:02 UTC+8',
        operationType: '跨仓拆单',
        operationResult: '成功',
        operator: '订单运营角色',
        content: '生成两张当前有效履约单；订单头保留首次默认路由。',
      },
      {
        operatedAt: '2026-09-09 11:18:04 UTC+2',
        operationType: '仓库出库',
        operationResult: '成功',
        operator: '仓库状态任务',
        content: '全部非取消应发数量已形成有效出库事实。',
      },
    ],
  },
  {
    systemOrderNo: 'OMS260910000233',
    platformCode: 'TikTok Shop',
    storeId: 'store-tiktok-uk-01',
    storeName: 'TikTok Shop 英国制动店',
    platformOrderId: 'tt-order-58***019',
    platformOrderNo: '5764***019',
    platformOrderType: 'NORMAL',
    platformOrderStatus: 'AWAITING_SHIPMENT',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    processingStatus: '异常',
    blockReason: '中台 SKU 映射查询失败，继续履约可能造成错发；当前已关闭发货门禁。',
    orderedAt: '2026-09-10 06:11:24 UTC+1',
    paidAt: '2026-09-10 06:12:07 UTC+1',
    shipByAt: '2026-09-11 15:00 UTC+1',
    shipByLabel: '明日 15:00',
    urgency: '正常',
    platformUpdatedAt: '2026-09-10 13:13:49 UTC+8',
    createdAt: '2026-09-10 13:14:03 UTC+8',
    lastSyncedAt: '2026-09-10 13:14:05 UTC+8',
    tags: ['阻'],
    buyerExternalId: 'tt***441',
    address: {
      fullName: 'S*** B***',
      mobilePhone: '+44 7*** *** 904',
      email: 's***@example.co.uk',
      countryCode: 'GB',
      stateProvince: 'Greater London',
      city: 'L***',
      addressLine1: '*** King Street',
      postalCode: 'E1 ***',
    },
    amount: {
      orderAmount: 金额值('GBP', '82.40'),
      buyerPaidShipping: 金额值('GBP', '4.90'),
      buyerPaidTax: 金额值('GBP', '13.73'),
    },
    items: [
      {
        externalLineId: 'tt-line-019-01',
        platformItemId: 'tt-item-***882',
        platformSku: 'TT-UK-BP-7702',
        platformVariant: 'Front axle',
        platformItemTitle: 'Low Dust Ceramic Brake Pad Set',
        orderedQuantity: 1,
        skuResolutionStatus: '查询失败',
        fulfillableQuantity: 0,
        currencyCode: 'GBP',
        unitPrice: 金额值('GBP', '82.40'),
        itemTotal: 金额值('GBP', '82.40'),
      },
    ],
    fulfillmentOrders: [],
    reviews: [
      {
        round: 1,
        type: '自动审核',
        triggerSource: '首次接入',
        status: '已拦截',
        decisionNote: '中台 SKU 映射查询失败；未形成订单头路由，禁止继续推仓。',
        completedAt: '2026-09-10 13:14:18 UTC+8',
      },
    ],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 13:14:05 UTC+8',
      latestAttempt: '2026-09-10 13:14:03 UTC+8',
      externalVersion: 'tt-v112908',
      normalizationStatus: '已标准化',
      message: '平台数据同步正常；异常来自中台 SKU 映射查询。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-10 13:14:03 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: 'TikTok Shop 接入任务',
        content: '创建全渠道订单。',
      },
      {
        operatedAt: '2026-09-10 13:14:18 UTC+8',
        operationType: '自动审核',
        operationResult: '失败',
        operator: '审单规则任务',
        content: 'SKU 映射查询失败，订单进入异常并关闭发货门禁。',
      },
    ],
  },
  {
    systemOrderNo: 'OMS260907000612',
    platformCode: 'Rakuten',
    storeId: 'store-rakuten-jp-01',
    storeName: '乐天日本滤清器店',
    platformOrderId: 'rk-order-20260907-***12',
    platformOrderNo: '20260907-***12',
    platformOrderType: 'NORMAL',
    platformOrderStatus: 'CANCELLED',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    processingStatus: '不发货',
    noShipmentReason: '平台已确认取消；OMS 发货量为零，未生成有效履约单。',
    cancelledAt: '2026-09-08 09:37:24 UTC+9',
    cancelledReason: '买家取消',
    orderedAt: '2026-09-07 18:03:18 UTC+9',
    paidAt: '2026-09-07 18:04:02 UTC+9',
    shipByLabel: '不适用',
    urgency: '无时限',
    platformUpdatedAt: '2026-09-08 09:37:24 UTC+9',
    createdAt: '2026-09-07 17:04:31 UTC+8',
    lastSyncedAt: '2026-09-10 12:48:12 UTC+8',
    tags: ['取'],
    buyerExternalId: 'rk***091',
    address: {
      fullName: 'Y*** T***',
      mobilePhone: '090-****-6128',
      email: 'y***@example.jp',
      countryCode: 'JP',
      stateProvince: 'Tokyo',
      city: 'Shin***',
      addressLine1: '***-** Nishi-Shinjuku',
      postalCode: '160-****',
    },
    amount: {
      orderAmount: 金额值('JPY', '9200'),
      buyerPaidShipping: 金额值('JPY', '600'),
      buyerPaidTax: 金额值('JPY', '836'),
    },
    items: [
      {
        externalLineId: 'rk-line-612-01',
        platformItemId: 'rk-item-***128',
        platformSku: 'RK-JP-AF-0312',
        platformItemTitle: 'Premium Cabin Air Filter',
        orderedQuantity: 2,
        systemSku: 'YY-AF-0312-JP',
        systemItemName: '活性炭空调滤芯',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 0,
        currencyCode: 'JPY',
        unitPrice: 金额值('JPY', '4300'),
        itemTotal: 金额值('JPY', '8600'),
        actualReceived: 金额值('JPY', '0'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [],
    reviews: [],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 12:48:12 UTC+8',
      latestAttempt: '2026-09-10 12:48:10 UTC+8',
      externalVersion: 'rk-cancel-77129',
      normalizationStatus: '已标准化',
      message: '已同步最终取消事实；订单无需 OMS 继续发货。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-07 17:04:31 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: '乐天接入任务',
        content: '创建全渠道订单。',
      },
      {
        operatedAt: '2026-09-08 08:37:41 UTC+8',
        operationType: '同步订单取消结果',
        operationResult: '成功',
        operator: '乐天增量任务',
        content: '记录已确认取消原因和取消时间；订单进入不发货。',
      },
    ],
  },
  {
    systemOrderNo: 'OMS260910000241',
    platformCode: 'eBay',
    storeId: 'store-ebay-au-01',
    storeName: 'eBay 澳洲冷却系统店',
    platformOrderId: '31-49028-77106',
    platformOrderNo: '31-49028-77106',
    platformOrderType: 'NORMAL',
    platformOrderStatus: 'NOT_STARTED',
    orderType: '线上订单',
    fulfillmentMode: '自配送',
    admissionReason: '付款证据仍待平台确认；全渠道订单已保存，但尚未进入订单处理。',
    orderedAt: '2026-09-10 14:02:31 UTC+10',
    shipByAt: '2026-09-12 16:00 UTC+10',
    shipByLabel: '后日 16:00',
    urgency: '正常',
    platformUpdatedAt: '2026-09-10 14:16:45 UTC+10',
    createdAt: '2026-09-10 12:17:03 UTC+8',
    lastSyncedAt: '2026-09-10 14:17:03 UTC+8',
    tags: ['待'],
    buyerExternalId: 'li***_auto',
    address: {
      fullName: 'L*** W***',
      mobilePhone: '+61 *** 55018',
      email: 'l***@example.au',
      countryCode: 'AU',
      stateProvince: 'NSW',
      city: 'S***',
      addressLine1: '*** Harbour Road',
      postalCode: '20**',
    },
    amount: {
      orderAmount: 金额值('AUD', '150.70'),
      buyerPaidShipping: 金额值('AUD', '18.00'),
      buyerPaidTax: 金额值('AUD', '13.70'),
    },
    items: [
      {
        externalLineId: 'v1|186093751009|0',
        platformItemId: '186093751009',
        platformSku: 'AU-RD-5106',
        platformItemTitle: 'Aluminum Radiator Cooling Assembly',
        orderedQuantity: 1,
        systemSku: 'YY-RD-5106-AU',
        systemItemName: '铝合金散热器总成',
        skuResolutionStatus: '成功',
        fulfillableQuantity: 1,
        currencyCode: 'AUD',
        unitPrice: 金额值('AUD', '150.70'),
        itemTotal: 金额值('AUD', '150.70'),
        actualReceived: 金额值('AUD', '150.70'),
        actualReceivedSource: 'PLATFORM',
      },
    ],
    fulfillmentOrders: [],
    reviews: [],
    sync: {
      status: '已同步',
      lastSuccess: '2026-09-10 14:17:03 UTC+8',
      latestAttempt: '2026-09-10 14:17:01 UTC+8',
      externalVersion: 'order@2026-09-10T04:16:45Z',
      normalizationStatus: '已标准化',
      message: '全渠道事实已更新；付款准入条件仍未满足。',
    },
    operationLogs: [
      {
        operatedAt: '2026-09-10 12:17:03 UTC+8',
        operationType: '订单接入',
        operationResult: '成功',
        operator: 'eBay 增量任务',
        content: '创建全渠道订单；付款证据待确认，未初始化 OMS 处理状态。',
      },
    ],
  },
]

export const 全渠道订单模拟数据: 全渠道订单[] = 全渠道订单场景.map((订单) => {
  if (订单.platformCode === 'eBay') return 订单

  return {
    ...订单,
    platformOrderStatus: undefined,
    lastSyncedAt: '—',
    tags: [...new Set(['占', ...订单.tags])],
    sync: {
      status: '未接入',
      latestAttempt: '—',
      normalizationStatus: '未接入',
      message: '该平台订单接口尚未对接；当前订单、状态与同步信息均为原型占位内容。',
    },
    operationLogs: [],
  }
})
